---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: buildbot
bases:
  - ../base

resources:
  - ingress.yaml

patches:
  - buildbot-master.cfg.yaml
  - buildbot-masters-config.yaml
  - buildbot-masters.yaml
  - buildbot-workers.yaml
  - crossbar.yaml
  - pg.yaml
